server:
  port: 9091
spring:
  application:
    name: springboot-admin-client
  boot:
    admin:
      client:
        url: http://localhost:9090
# 暴露所有的actuator断点信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    path: /var/logs/${spring.application.name}/admin-client/
    name: springboot-admin-client.log